applications:
  app-n8n:
    type: 'nodejs:22'
    variables:
      env:
        N8N_EMAIL_MODE: 'smtp'
        N8N_SMTP_PORT: "25"
        N8N_SMTP_SSL: false
        N8N_RUNNERS_ENABLED: true
    dependencies:
      nodejs:
        n8n: "*"
        n8n-nodes-mcp: "*"
    mounts:
      '.n8n': { source: storage, source_path: n8n }
      '.cache': { source: storage, source_path: cache }
    web:
      commands:
        start: "n8n start"
      upstream:
        socket_family: tcp
        protocol: http
      locations:
        '/':
          
          
          passthru: true
          request_buffering:
            enabled: false
    hooks:
      build: |
        set -xeu
        echo 'export N8N_PORT=$PORT' >> .environment
routes:
    "https://{all}/": { type: upstream, upstream: "app-n8n:http", primary: true, cache: {enabled: false}}
    "http://{all}/": { type: redirect, to: "https://{all}/" }
